name: Green Checks

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  green-checks:
    runs-on: ubuntu-latest

    steps:

      - name: Cache Yarn Classic
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/yarn
            frontend/node_modules
          key: yarn-classic-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            yarn-classic-

      - name: Cache Yarn Berry
        uses: actions/cache@v5
        with:
          path: |
            frontend/.yarn/cache
            frontend/.pnp.cjs
          key: yarn-berry-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            yarn-berry-

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      # -----------------------------
      # ECOCODE
      # -----------------------------
      - name: Switch to frontend directory
        working-directory: frontend
        run: |
         corepack enable
         yarn install --immutable
        env: 
          PLUGIN_ID: activemq-classic 
          PLUGIN_SCOPE: activemqClassic 
          PLUGIN_MODULE: plugin

      - name: Ensure reports directory exists
        run: mkdir -p reports

      - name: Execute creedengo scan
        working-directory: frontend
        run: |
         npx eslint . -f json -o ../reports/creedengo.json || true
        env: 
          PLUGIN_ID: activemq-classic 
          PLUGIN_SCOPE: activemqClassic 
          PLUGIN_MODULE: plugin

      # -----------------------------
      # OVERALL SCORE
      # -----------------------------
      - name: Compute overall score
        run: node .github/scripts/compute-overall.mjs

      # -----------------------------
      # BADGES
      # -----------------------------
      - name: Generate badges
        run: node .github/scripts/generate-badge.mjs

      # -----------------------------
      # EXTRACT SCORES
      # -----------------------------
      - name: Extract scores
        id: scores
        run: |
          echo "CREEDENGO=$(jq -r '.creedengo' reports/overall.json)" >> $GITHUB_ENV
          echo "TOTAL=$(jq -r '.total' reports/overall.json)" >> $GITHUB_ENV
      
      # -----------------------------
      # COMMENTO PR
      # -----------------------------
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          recreate: true
          message: |
            ## 🌱 Green Checks Report
            **Creedengo:** ${{ env.CREEDENGO }}
            **Overall:** ${{ env.TOTAL }}

      # -----------------------------
      # RELEASE
      # -----------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: green-checks
          path: |
            reports/
            badges/
